#!/bin/bash

VPNC_FILE='/sys/class/net/tun0/dev_id'

if [[ -e "${VPNC_FILE}" ]]; then
  echo "<span color='#00FF00'><span font_desc='FontAwesome'></span> ON</span>"
#  echo "on"
else
  echo "<span color='red'><span font_desc='FontAwesome'></span> OFF</span>"
#  echo ""
fi
